[colors.primary]
background = "#730f20"
foreground = "#8cf0df"

[colors.normal]
black = "#1c0308"
red = "#8c0308"
green = "#1cf008"
yellow = "#8cf008"
blue = "#1c03df"
magenta = "#8c03df"
cyan = "#1cf0df"
white = "#8cf0df"

[colors.bright]
black = "#390710"
red = "#ff0710"
green = "#39ff10"
yellow = "#ffff10"
blue = "#3907ff"
magenta = "#ff07ff"
cyan = "#39ffff"
white = "#ffffff"
