[colors.primary]
background = "#4c2323"
foreground = "#b3dcdc"

[colors.normal]
black = "#130808"
red = "#b30808"
green = "#13dc08"
yellow = "#b3dc08"
blue = "#1308dc"
magenta = "#b308dc"
cyan = "#13dcdc"
white = "#b3dcdc"

[colors.bright]
black = "#261111"
red = "#ff1111"
green = "#26ff11"
yellow = "#ffff11"
blue = "#2611ff"
magenta = "#ff11ff"
cyan = "#26ffff"
white = "#ffffff"
